# Generated by Django 6.0.2 on 2026-03-24 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_taskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='issue_type',
            field=models.CharField(choices=[('epic', 'Epic'), ('story', 'Story'), ('task', 'Task'), ('bug', 'Bug'), ('subtask', 'Subtask')], default='task', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='core.task'),
        ),
    ]
