# Generated by Django 6.0.2 on 2026-03-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_taskactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='task',
            name='time_spent',
            field=models.FloatField(default=0.0),
        ),
    ]
