# Generated by Django 6.0.2 on 2026-03-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='assigned_to',
        ),
    ]
